### ISSUE TITLE
Takeover process

### ISSUE THREAD

**Issue by lierdakil** [haskell-hvr/int-cast#8]
As per @andreasabel's request in #5, a checklist for the takeover process:

- [x] Try to contact the maintainer. 

    Sent an e-mail to hvr@gnu.org on July 5th.
- [x] Give them reasonable time to respond.
- [x] State your intention to take over the package in a public forum (we recommend the haskell discourse and/or the haskell-cafe). CC the maintainer.

    https://mail.haskell.org/pipermail/haskell-cafe/2023-July/136262.html
    https://discourse.haskell.org/t/taking-over-maintenance-of-int-cast-package/7024
- [x] Wait a while.
- [x] Send an email to the hackage administrators ([hackage-admin@haskell.org](mailto:hackage-admin@haskell.org)), with a link to the public email thread.
- [ ] The admins will grant you maintenance rights or upload a patched version for you.

**Comment by lierdakil** [comment]
FTR, moving on with the process:

https://mail.haskell.org/pipermail/haskell-cafe/2023-July/136262.html
https://discourse.haskell.org/t/taking-over-maintenance-of-int-cast-package/7024

**Comment by lierdakil** [comment]
I've finally emailed hackage-admin, but @hvr immediately responded to block that, despite not reacting to a couple previous emails on the topic. So yeah... Welp, unless he positively responds to my offer for joint maintenance — and I'm not holding my breath — I guess that's it, no further action possible.

/cc @andreasabel in case you want an update.

**Comment by andreasabel** [comment]
@lierdakil : It's unfortunate how this went, but Herbert seems to like to keep this package, so that has to be respected, of course.  
I checked the status of `int-cast` on Stackage and it seems to be a leaf there (no packages depend on it).  On Hackage, I found `LambdaHack` and `morley` (that must be you!) as direct users.
You can decide to fork it, which is a bit sad always; but maybe Herbert takes up your offer...
